package main

import (
	"fmt"
	"log"
	"os"

	"teamwork-test-task/internal/customerimporter"
)

func main() {
	customImporter, err := customerimporter.NewCustomerImporter("data/customers.csv", "email")
	if err != nil {
		log.Println(err)
		os.Exit(1)
	}

	customerCountByDomain, err := customImporter.GetDomainCounts()
	if err != nil {
		log.Println(err)
		os.Exit(1)
	}

	for _, domain := range customerCountByDomain {
		fmt.Printf("%s - %d \n", domain.Domain, domain.CustomerCount)
	}
}

/*
Output:

2023/11/20 00:49:11 invalid email address found in row [first_name last_name email gender ip_address], skipping
2023/11/20 00:49:11 invalid email address found in row [first_name last_name email gender ip_address], skipping
loc.gov - 14
domainmarket.com - 13
reddit.com - 13
geocities.com - 12
weebly.com - 12
miitbeian.gov.cn - 12
studiopress.com - 12
google.fr - 12
go.com - 11
google.de - 11
cisco.com - 11
desdev.cn - 11
independent.co.uk - 11
stanford.edu - 11
networkadvertising.org - 11
vk.com - 11
nymag.com - 11
shinystat.com - 10
jiathis.com - 10
opera.com - 10
sfgate.com - 10
freewebs.com - 10
bbc.co.uk - 10
google.co.uk - 10
sun.com - 10
buzzfeed.com - 10
woothemes.com - 10
huffingtonpost.com - 10
kickstarter.com - 10
seattletimes.com - 10
dagondesign.com - 10
behance.net - 10
washingtonpost.com - 10
rambler.ru - 10
elpais.com - 10
globo.com - 10
addthis.com - 10
squarespace.com - 10
hibu.com - 10
ftc.gov - 9
ifeng.com - 9
nifty.com - 9
whitehouse.gov - 9
hostgator.com - 9
xing.com - 9
photobucket.com - 9
yolasite.com - 9
ca.gov - 9
arstechnica.com - 9
mit.edu - 9
squidoo.com - 9
ovh.net - 9
irs.gov - 9
hubpages.com - 9
google.com - 9
slideshare.net - 9
tinyurl.com - 9
nhs.uk - 9
sina.com.cn - 9
earthlink.net - 9
elegantthemes.com - 9
t-online.de - 9
tiny.cc - 9
ezinearticles.com - 9
i2i.jp - 9
google.ru - 9
bloomberg.com - 9
dailymail.co.uk - 9
google.es - 9
oakley.com - 9
sphinn.com - 9
admin.ch - 9
rediff.com - 9
ihg.com - 9
usnews.com - 8
epa.gov - 8
time.com - 8
123-reg.co.uk - 8
unblog.fr - 8
skype.com - 8
unc.edu - 8
wisc.edu - 8
symantec.com - 8
ucsd.edu - 8
hexun.com - 8
zdnet.com - 8
netlog.com - 8
cbsnews.com - 8
vistaprint.com - 8
wiley.com - 8
slashdot.org - 8
prweb.com - 8
livejournal.com - 8
purevolume.com - 8
free.fr - 8
typepad.com - 8
newsvine.com - 8
myspace.com - 8
nasa.gov - 8
github.io - 8
edublogs.org - 8
smugmug.com - 8
army.mil - 8
guardian.co.uk - 8
smh.com.au - 8
indiegogo.com - 8
patch.com - 8
icq.com - 8
netvibes.com - 8
twitter.com - 8
cbslocal.com - 8
goo.gl - 8
craigslist.org - 8
blogger.com - 8
example.com - 8
rakuten.co.jp - 8
harvard.edu - 8
wired.com - 8
twitpic.com - 8
tamu.edu - 8
imageshack.us - 8
storify.com - 8
constantcontact.com - 8
google.com.au - 8
barnesandnoble.com - 8
lulu.com - 7
hao123.com - 7
facebook.com - 7
yale.edu - 7
ucla.edu - 7
abc.net.au - 7
forbes.com - 7
wordpress.org - 7
dion.ne.jp - 7
mlb.com - 7
liveinternet.ru - 7
mac.com - 7
comsenz.com - 7
sogou.com - 7
issuu.com - 7
blogtalkradio.com - 7
cocolog-nifty.com - 7
cbc.ca - 7
archive.org - 7
baidu.com - 7
sakura.ne.jp - 7
flavors.me - 7
mozilla.com - 7
usatoday.com - 7
pinterest.com - 7
tripod.com - 7
altervista.org - 7
yahoo.com - 7
yellowpages.com - 7
taobao.com - 7
chronoengine.com - 7
sourceforge.net - 7
github.com - 7
marketwatch.com - 7
tumblr.com - 7
nature.com - 7
stumbleupon.com - 7
tuttocitta.it - 7
bloglovin.com - 7
microsoft.com - 7
berkeley.edu - 7
google.nl - 7
canalblog.com - 7
amazon.de - 7
eepurl.com - 7
deliciousdays.com - 7
unesco.org - 7
ehow.com - 7
chicagotribune.com - 7
nydailynews.com - 7
walmart.com - 7
deviantart.com - 7
wp.com - 7
live.com - 7
prnewswire.com - 7
telegraph.co.uk - 7
macromedia.com - 7
alibaba.com - 7
e-recht24.de - 7
so-net.ne.jp - 7
census.gov - 7
blinklist.com - 7
google.ca - 7
skyrock.com - 7
sitemeter.com - 6
163.com - 6
princeton.edu - 6
engadget.com - 6
unicef.org - 6
hugedomains.com - 6
pbs.org - 6
oaic.gov.au - 6
paginegialle.it - 6
amazon.com - 6
reuters.com - 6
printfriendly.com - 6
a8.net - 6
ask.com - 6
mtv.com - 6
devhub.com - 6
nsw.gov.au - 6
cdc.gov - 6
lycos.com - 6
parallels.com - 6
prlog.org - 6
alexa.com - 6
upenn.edu - 6
csmonitor.com - 6
toplist.cz - 6
g.co - 6
ow.ly - 6
addtoany.com - 6
delicious.com - 6
phpbb.com - 6
geocities.jp - 6
acquirethisname.com - 6
tripadvisor.com - 6
etsy.com - 6
psu.edu - 6
youtu.be - 6
cyberchimps.com - 6
msn.com - 6
statcounter.com - 6
noaa.gov - 6
disqus.com - 6
360.cn - 6
cnbc.com - 6
ycombinator.com - 6
shutterfly.com - 6
phoca.cz - 6
shareasale.com - 6
nih.gov - 6
mysql.com - 6
nationalgeographic.com - 6
amazonaws.com - 6
wikia.com - 6
blog.com - 6
instagram.com - 6
tmall.com - 6
hud.gov - 6
biblegateway.com - 6
accuweather.com - 6
reverbnation.com - 6
tinypic.com - 6
adobe.com - 6
cnet.com - 6
chron.com - 6
wikimedia.org - 6
moonfruit.com - 6
uiuc.edu - 6
last.fm - 6
blogspot.com - 6
google.pl - 6
goo.ne.jp - 6
over-blog.com - 6
usda.gov - 6
w3.org - 6
odnoklassniki.ru - 6
fc2.com - 6
illinois.edu - 6
xinhuanet.com - 6
merriam-webster.com - 6
si.edu - 6
cargocollective.com - 6
sbwire.com - 6
ameblo.jp - 6
bloglines.com - 6
cafepress.com - 6
marriott.com - 6
umich.edu - 6
nba.com - 5
hc360.com - 5
yandex.ru - 5
examiner.com - 5
angelfire.com - 5
creativecommons.org - 5
wikipedia.org - 5
samsung.com - 5
google.co.jp - 5
theatlantic.com - 5
auda.org.au - 5
1und1.de - 5
arizona.edu - 5
paypal.com - 5
discuz.net - 5
amazon.co.jp - 5
senate.gov - 5
flickr.com - 5
bravesites.com - 5
japanpost.jp - 5
seesaa.net - 5
hhs.gov - 5
mail.ru - 5
feedburner.com - 5
indiatimes.com - 5
exblog.jp - 5
oracle.com - 5
cam.ac.uk - 5
foxnews.com - 5
artisteer.com - 5
discovery.com - 5
weibo.com - 5
fotki.com - 5
google.cn - 5
google.com.br - 5
opensource.org - 5
ucoz.com - 5
webmd.com - 5
qq.com - 5
howstuffworks.com - 5
surveymonkey.com - 5
dropbox.com - 5
gnu.org - 5
usgs.gov - 5
apple.com - 5
sciencedaily.com - 5
ebay.co.uk - 5
ft.com - 5
webnode.com - 5
mashable.com - 5
multiply.com - 5
jimdo.com - 5
springer.com - 5
china.com.cn - 5
yahoo.co.jp - 5
utexas.edu - 5
redcross.org - 5
fema.gov - 5
spotify.com - 5
weather.com - 5
answers.com - 5
salon.com - 5
google.com.hk - 5
aol.com - 5
bbb.org - 5
4shared.com - 5
youku.com - 5
jugem.jp - 5
omniture.com - 5
clickbank.net - 5
webs.com - 5
timesonline.co.uk - 5
house.gov - 5
bluehost.com - 5
businessinsider.com - 5
ibm.com - 5
diigo.com - 5
histats.com - 5
mapy.cz - 5
about.com - 5
gmpg.org - 5
nbcnews.com - 5
com.com - 5
is.gd - 5
mapquest.com - 5
uol.com.br - 5
scribd.com - 5
theglobeandmail.com - 5
mayoclinic.com - 5
wsj.com - 5
yellowbook.com - 5
dmoz.org - 5
umn.edu - 5
vinaora.com - 5
virginia.edu - 5
gizmodo.com - 5
naver.com - 5
godaddy.com - 5
biglobe.ne.jp - 4
plala.or.jp - 4
yelp.com - 4
miibeian.gov.cn - 4
meetup.com - 4
soup.io - 4
51.la - 4
hp.com - 4
sohu.com - 4
boston.com - 4
usa.gov - 4
bing.com - 4
blogs.com - 4
columbia.edu - 4
cmu.edu - 4
furl.net - 4
slate.com - 4
cdbaby.com - 4
dedecms.com - 4
sciencedirect.com - 4
friendfeed.com - 4
washington.edu - 4
wix.com - 4
privacy.gov.au - 4
simplemachines.org - 4
hatena.ne.jp - 4
nyu.edu - 4
pagesperso-orange.fr - 4
booking.com - 4
eventbrite.com - 4
gov.uk - 4
cornell.edu - 4
topsy.com - 4
fastcompany.com - 4
google.it - 4
ebay.com - 4
gravatar.com - 4
mediafire.com - 4
webeden.co.uk - 4
scientificamerican.com - 4
wordpress.com - 4
pen.io - 4
ocn.ne.jp - 4
techcrunch.com - 4
people.com.cn - 4
cnn.com - 4
ustream.tv - 4
dot.gov - 4
dell.com - 4
pcworld.com - 4
cpanel.net - 4
wikispaces.com - 4
infoseek.co.jp - 4
reference.com - 4
intel.com - 4
thetimes.co.uk - 4
dyndns.org - 4
de.vu - 4
state.tx.us - 4
netscape.com - 4
1688.com - 3
quantcast.com - 3
npr.org - 3
zimbio.com - 3
ox.ac.uk - 3
nps.gov - 3
wunderground.com - 3
icio.us - 3
goodreads.com - 3
theguardian.com - 3
bandcamp.com - 3
economist.com - 3
cloudflare.com - 3
comcast.net - 3
networksolutions.com - 3
state.gov - 3
list-manage.com - 3
amazon.co.uk - 3
who.int - 3
shop-pro.jp - 3
drupal.org - 3
nytimes.com - 3
home.pl - 3
posterous.com - 3
soundcloud.com - 3
youtube.com - 3
ed.gov - 3
vimeo.com - 3
newyorker.com - 3
businessweek.com - 3
technorati.com - 3
t.co - 3
va.gov - 3
msu.edu - 3
fda.gov - 2
aboutads.info - 2
java.com - 2
xrea.com - 2
bizjournals.com - 2
jalbum.net - 2
themeforest.net - 2
europa.eu - 2
homestead.com - 2
digg.com - 2
imdb.com - 2
wufoo.com - 2
linkedin.com - 2
spiegel.de - 2
about.me - 2
imgur.com - 2
joomla.org - 2
istockphoto.com - 2
jigsy.com - 2
vkontakte.ru - 2
narod.ru - 2
trellian.com - 2
bigcartel.com - 2
apache.org - 2
ucoz.ru - 2
mozilla.org - 2
php.net - 2
latimes.com - 2
businesswire.com - 2
dailymotion.com - 1
un.org - 1
ning.com - 1
ted.com - 1
*/
